project_id = "fuohmclakezkvgaiarao"

[functions.whatsapp-bot]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.baileys-session]
verify_jwt = false

[functions.hybrid-websocket]
verify_jwt = false

[functions.business-api]
verify_jwt = false