[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = ["npm install --legacy-peer-deps"]

[start]
cmd = "npm start"
[build]
builder = "NIXPACKS"

[build.nixpacksPlan.env]
NODE_VERSION = "20"
